version: "3.8"

services:
  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      replicas: 3
    command: ["npm", "start"]
    networks:
      - app-network  # Thêm vào mạng chung

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    healthcheck: 
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network  # Kết nối vào mạng chung

  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network  # Kết nối vào mạng chung

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: abc
      RABBITMQ_DEFAULT_PASS: 1234
    networks:
      - app-network 

volumes:
  mongo-data:

networks:
  app-network:  
    driver: bridge